version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DB: attdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Mount db folder with SQL backup file
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres --password Ti100600@"]
      interval: 10s
      retries: 5

  db-restore:
    image: postgres  # Use PostgreSQL image to run the restore script
    depends_on:
      - postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint: ["/docker-entrypoint-initdb.d/restore.sh"]  # Run the restore script
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DB: attdb
    restart: "no"


  server:
    build: ./server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DATABASE: attdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
      - db-restore
    ports:
      - "3002:3000"
    volumes:
      - ./server:/app
    command: "npm run start"  # Adjust based on your server start command
