version: '3.8'
services:
  postgres:
    build: ./db
    image: nguyentien0620/postgres-init
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DB: attdb
    ports:
      - "5432:5432"
    platform: linux/arm64/v8
    

  server:
    build: ./server
    image: nguyentien0620/server-arm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ti100600@
      POSTGRES_DATABASE: attdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      SERVER_HOST: 3002
    depends_on:
      - postgres
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
    command: "npm run start"  # Adjust based on your server start command
    platform: linux/arm64/v8

  client:
    build: ./client
    image: nguyentien0620/client-arm
    environment:
      VITE_WS_URL: ws://127.0.0.1:3002
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    platform: linux/arm64/v8