--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+2)
-- Dumped by pg_dump version 16.4

-- Started on 2024-11-11 14:26:26 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16388)
-- Name: Attendances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attendances" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "VerifyDate" timestamp without time zone NOT NULL,
    "DeviceName" text,
    "UserName" text,
    "UserId" text,
    "Name" text,
    "Uploaded" boolean
);


ALTER TABLE public."Attendances" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16393)
-- Name: Attendances_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attendances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attendances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16394)
-- Name: Devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Devices" (
    "Id" integer NOT NULL,
    "Ip" text NOT NULL,
    "Port" text NOT NULL,
    "CommKey" text NOT NULL,
    "IsConnected" boolean NOT NULL,
    "Name" text
);


ALTER TABLE public."Devices" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16399)
-- Name: Devices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Devices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Devices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16400)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Password" text NOT NULL,
    "Role" integer NOT NULL,
    "CardNo" text NOT NULL,
    "DisplayName" name COLLATE pg_catalog."default",
    "DeviceIp" text,
    "UID" integer,
    "UserId" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16405)
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16406)
-- Name: Settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Settings" (
    "Id" smallint NOT NULL,
    "Email" text,
    "Password" text
);


ALTER TABLE public."Settings" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16411)
-- Name: Settings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Settings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Settings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2000
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16412)
-- Name: Sheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sheets" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "SheetName" text NOT NULL,
    "DocumentId" text NOT NULL
);


ALTER TABLE public."Sheets" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16417)
-- Name: Sheets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sheets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sheets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16418)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3228 (class 2606 OID 16422)
-- Name: Attendances PK_Attendances; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attendances"
    ADD CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id");


--
-- TOC entry 3230 (class 2606 OID 16424)
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY ("Id");


--
-- TOC entry 3232 (class 2606 OID 16426)
-- Name: Users PK_Employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- TOC entry 3237 (class 2606 OID 16428)
-- Name: Sheets PK_Sheets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "PK_Sheets" PRIMARY KEY ("Id");


--
-- TOC entry 3239 (class 2606 OID 16430)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3234 (class 2606 OID 16432)
-- Name: Settings Settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Settings"
    ADD CONSTRAINT "Settings_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3235 (class 1259 OID 16433)
-- Name: IX_Sheets_DeviceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sheets_DeviceId" ON public."Sheets" USING btree ("DeviceId");


--
-- TOC entry 3240 (class 2606 OID 16434)
-- Name: Sheets FK_Sheets_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "FK_Sheets_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


-- Completed on 2024-11-11 14:26:28 UTC

--
-- PostgreSQL database dump complete
--

INSERT INTO public."Settings"(
"Email", "Password")
	VALUES ('admin@gmail.com', 'admin');

INSERT INTO public."Settings"(
"Email", "Password")
	VALUES ('mcc.sanabox@gmail.com', 'admin');