--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4

-- Started on 2024-11-05 07:13:03 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 65637)
-- Name: Attendances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attendances" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "VerifyDate" timestamp with time zone NOT NULL,
    "DeviceName" text,
    "UserName" text,
    "UserId" text,
    "Name" text,
    "Uploaded" boolean
);


ALTER TABLE public."Attendances" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 65642)
-- Name: Attendances_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attendances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attendances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 65643)
-- Name: Devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Devices" (
    "Id" integer NOT NULL,
    "Ip" text NOT NULL,
    "Port" text NOT NULL,
    "CommKey" text NOT NULL,
    "IsConnected" boolean NOT NULL,
    "Name" text
);


ALTER TABLE public."Devices" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 65648)
-- Name: Devices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Devices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Devices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 65649)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Password" text NOT NULL,
    "Role" integer NOT NULL,
    "CardNo" text NOT NULL,
    "DisplayName" name COLLATE pg_catalog."default",
    "DeviceIp" text,
    "UID" integer,
    "UserId" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 65654)
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 73828)
-- Name: Settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Settings" (
    "Id" integer DEFAULT 1 NOT NULL,
    "Email" text
);


ALTER TABLE public."Settings" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 65655)
-- Name: Sheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sheets" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "SheetName" text NOT NULL,
    "DocumentId" text NOT NULL
);


ALTER TABLE public."Sheets" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 65660)
-- Name: Sheets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sheets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sheets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 65661)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3384 (class 0 OID 65637)
-- Dependencies: 215
-- Data for Name: Attendances; Type: TABLE DATA; Schema: public; Owner: postgres
--

-- COPY public."Attendances" ("Id", "DeviceId", "VerifyDate", "DeviceName", "UserName", "UserId", "Name", "Uploaded") FROM stdin;
-- 112	1	2024-10-30 02:07:02+00	Cổng chính	nguyentien	1234567	Nguyễn Tiến	t
-- 97	1	2024-10-31 00:00:08+00	Cổng chính	nguyentien	12345	Nguyễn Tiến	t
-- 99	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- 98	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien	123456	Nguyễn Tiến	t
-- 108	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- 107	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- 106	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- 104	1	2024-10-10 00:00:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- 105	1	2024-10-10 03:03:00+00	Cổng chính	nguyentien 1	123456	Nguyễn Tiến 1	t
-- \.


--
-- TOC entry 3386 (class 0 OID 65643)
-- Dependencies: 217
-- Data for Name: Devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Devices" ("Id", "Ip", "Port", "CommKey", "IsConnected", "Name") FROM stdin;
1	192.168.1.201	4370	0	f	Cổng chính
2	192.168.1.235	4370	0	f	Cổng phụ
\.


--
-- TOC entry 3393 (class 0 OID 73828)
-- Dependencies: 224
-- Data for Name: Settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Settings" ("Id", "Email") FROM stdin;
\.


--
-- TOC entry 3390 (class 0 OID 65655)
-- Dependencies: 221
-- Data for Name: Sheets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sheets" ("Id", "DeviceId", "SheetName", "DocumentId") FROM stdin;
2	1	Sheet1	1xdgwVu8Cbg19EYvwg8bwhrW0d-Q9ZNFv9AahfuhNpFE
1	1	Sheet1	1J_ksu0COMPtBoddnHp-r4qvAriS3Ddg3hsTo3-OUnXo
\.


--
-- TOC entry 3388 (class 0 OID 65649)
-- Dependencies: 219
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Password", "Role", "CardNo", "DisplayName", "DeviceIp", "UID", "UserId") FROM stdin;
1	nguyenvantien	123456	0	0	Nguyễn Văn Tiến	192.168.1.201	1	123456
2	nguyenvantien1	123456	1	0	Nguyễn Văn Tiến 1	192.168.1.235	1	123457\n
3	nguyenvantien3	123456	2	0	Nguyễn Văn Tiến 3	192.168.1.201	1	123458
4	nguyenvantien4	123456	3	0	Nguyễn Văn Tiến 4	192.168.1.201	1	123459
\.


--
-- TOC entry 3392 (class 0 OID 65661)
-- Dependencies: 223
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
\.


--
-- TOC entry 3399 (class 0 OID 0)
-- Dependencies: 216
-- Name: Attendances_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Attendances_Id_seq"', 112, true);


--
-- TOC entry 3400 (class 0 OID 0)
-- Dependencies: 218
-- Name: Devices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Devices_Id_seq"', 36, true);


--
-- TOC entry 3401 (class 0 OID 0)
-- Dependencies: 220
-- Name: Employees_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Employees_Id_seq"', 2929, true);


--
-- TOC entry 3402 (class 0 OID 0)
-- Dependencies: 222
-- Name: Sheets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sheets_Id_seq"', 41, true);


--
-- TOC entry 3228 (class 2606 OID 65665)
-- Name: Attendances PK_Attendances; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attendances"
    ADD CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id");


--
-- TOC entry 3230 (class 2606 OID 65667)
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY ("Id");


--
-- TOC entry 3232 (class 2606 OID 65669)
-- Name: Users PK_Employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- TOC entry 3235 (class 2606 OID 65671)
-- Name: Sheets PK_Sheets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "PK_Sheets" PRIMARY KEY ("Id");


--
-- TOC entry 3237 (class 2606 OID 65673)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3239 (class 2606 OID 73835)
-- Name: Settings Settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Settings"
    ADD CONSTRAINT "Settings_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3233 (class 1259 OID 65674)
-- Name: IX_Sheets_DeviceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sheets_DeviceId" ON public."Sheets" USING btree ("DeviceId");


--
-- TOC entry 3240 (class 2606 OID 65675)
-- Name: Sheets FK_Sheets_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "FK_Sheets_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


-- Completed on 2024-11-05 07:13:03 UTC

--
-- PostgreSQL database dump complete
--

