export const RequestTypes = {
    AddDevice: "Device.Add",
    RemoveDevice: "Device.Remove",
    UpdateDevice: "Device.Update",
    ConnectDevice: "Device.Connect",
    GetDevices: "Device.GetAll",
    DisconnectDevice: "Device.Disconnect",
    GetUsers: "User.GetUsers",
    AddUser: "User.Add",
    DeleteUser: "User.Delete",
    GetAllUsers: "User.GetAll",
    SyncUserData: "User.SyncData",    
    PullUserData: "User.PullData",
    GetUsersByDeviceId: "User.GetByDeviceId",
    EditUser: "User.Edit",
    GetAttendances: "Attendance.GetAll",
    SyncLogData: "Attendance.SyncAttendance",
    SyncData: "Attendance.SyncAttendances",
    UpdateLog: "Attendance.Update",
    DeleteLog: "Attendance.Delete",
    AddLog: "Attendance.Add",
    SyncDataFromSheet: "Attendance.SyncDataFromSheet",
    GetSheets: "GetSheets",
    UpdateEmail: "UpdateEmail",
    GetSettings: "GetSettings",
    SyncTime: "SyncTime",
    ChangePassword: "ChangePassword"
}
