--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-13 10:50:18 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 33299)
-- Name: Attendances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attendances" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "VerifyDate" timestamp with time zone NOT NULL,
    "DeviceName" text,
    "UserName" text,
    "UserId" text
);


ALTER TABLE public."Attendances" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 33298)
-- Name: Attendances_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attendances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attendances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33342)
-- Name: DeviceEmployees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DeviceEmployees" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "EmployeeId" integer NOT NULL
);


ALTER TABLE public."DeviceEmployees" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 33341)
-- Name: DeviceEmployees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DeviceEmployees" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DeviceEmployees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 33305)
-- Name: Devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Devices" (
    "Id" integer NOT NULL,
    "Ip" text NOT NULL,
    "Port" text NOT NULL,
    "CommKey" text NOT NULL,
    "IsConnected" boolean NOT NULL,
    "Name" text
);


ALTER TABLE public."Devices" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 33304)
-- Name: Devices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Devices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Devices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 33313)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Password" text NOT NULL,
    "Role" integer NOT NULL,
    "CardNo" text NOT NULL,
    "DisplayName" name COLLATE pg_catalog."default",
    "DeviceIp" text,
    "UID" integer,
    "UserId" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 33312)
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 33321)
-- Name: Notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notifications" (
    "Id" integer NOT NULL,
    "CreateAt" timestamp without time zone NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "Success" boolean NOT NULL
);


ALTER TABLE public."Notifications" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 33320)
-- Name: Notifications_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notifications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notifications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33329)
-- Name: Sheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sheets" (
    "Id" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "SheetName" text NOT NULL,
    "DocumentId" text NOT NULL
);


ALTER TABLE public."Sheets" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 33328)
-- Name: Sheets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sheets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sheets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 33293)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3397 (class 0 OID 33299)
-- Dependencies: 217
-- Data for Name: Attendances; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Attendances" ("Id", "DeviceId", "VerifyDate", "DeviceName", "UserName", "UserId") FROM stdin;
7	30	2000-02-02 00:00:00+00	Cổng 4	Tien	1000
8	30	2024-10-12 10:28:09.827247+00	Cổng 4	Tien	1000
9	30	2024-10-12 10:28:55.775304+00	Cổng 4	Tien	1000
10	30	2024-10-12 10:40:30.585886+00	Cổng 4	Tien	1000
11	30	2024-10-12 10:41:21.12774+00	Cổng 4	Tien	1000
12	30	2024-10-12 10:45:52.701304+00	Cổng 4	Tien	1000
13	30	2024-10-12 10:47:39.005214+00	Cổng 4	Tiến	1000
14	32	2024-10-12 11:11:11.609906+00	Cổng phụ 1	88	1
\.


--
-- TOC entry 3407 (class 0 OID 33342)
-- Dependencies: 227
-- Data for Name: DeviceEmployees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."DeviceEmployees" ("Id", "DeviceId", "EmployeeId") FROM stdin;
\.


--
-- TOC entry 3399 (class 0 OID 33305)
-- Dependencies: 219
-- Data for Name: Devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Devices" ("Id", "Ip", "Port", "CommKey", "IsConnected", "Name") FROM stdin;
34	192.168.1.201	4370	0	t	Cổng 3
29	192.168.1.235	4370	0	t	cổng chính
\.


--
-- TOC entry 3403 (class 0 OID 33321)
-- Dependencies: 223
-- Data for Name: Notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Notifications" ("Id", "CreateAt", "Message", "IsRead", "Success") FROM stdin;
1	2024-09-20 23:29:47.488545	Device $192.168.1.201: Added successfully!	f	t
2	2024-09-21 00:23:26.204334	Device 192.168.1.201: Employee added failed	f	f
3	2024-09-22 22:35:51.261377	Device 192.168.1.201: Cann't Disconnect due to unconnected.	f	f
4	2024-09-22 22:36:45.219499	Device $192.168.1.201: Added successfully!	f	t
5	2024-09-22 22:37:08.964235	Device 192.168.1.201: Connected failed!	f	f
6	2024-09-22 22:40:43.834356	Device 192.168.1.201: Initialized sheet Sheet1 (ID: 123) failed because $The service sheets has thrown an exception. HttpStatusCode is NotFound. Requested entity was not found.	f	t
7	2024-09-22 22:45:01.978869	Device 192.168.1.201: Cann't Disconnect due to unconnected.	f	f
8	2024-09-22 22:47:34.241919	Device $192.168.1.201: Added successfully!	f	t
9	2024-09-22 22:47:43.351744	Device 192.168.1.201: Initialized sheet Sheet1 (ID: v) failed because $The service sheets has thrown an exception. HttpStatusCode is NotFound. Requested entity was not found.	f	t
10	2024-09-22 22:47:43.386905	Device 192.168.1.201: Connected successfully!	f	t
11	2024-09-22 22:47:54.726397	Device 192.168.1.201: Employee added successfully!	f	t
\.


--
-- TOC entry 3405 (class 0 OID 33329)
-- Dependencies: 225
-- Data for Name: Sheets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sheets" ("Id", "DeviceId", "SheetName", "DocumentId") FROM stdin;
33	29	Sheet1	1xdgwVu8Cbg19EYvwg8bwhrW0d-Q9ZNFv9AahfuhNpFE
39	34	Sheet1	1J_ksu0COMPtBoddnHp-r4qvAriS3Ddg3hsTo3-OUnXo
40	29	Sheet1	1J_ksu0COMPtBoddnHp-r4qvAriS3Ddg3hsTo3-OUnXo
41	34	Sheet2	1xdgwVu8Cbg19EYvwg8bwhrW0d-Q9ZNFv9AahfuhNpFE
\.


--
-- TOC entry 3401 (class 0 OID 33313)
-- Dependencies: 221
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Password", "Role", "CardNo", "DisplayName", "DeviceIp", "UID", "UserId") FROM stdin;
2561	hanghr		0	0	hanghr	192.168.1.235	3	502
2562	dvthanhsang		0	0	dvthanhsang	192.168.1.235	4	503
2563	cn8nguyenthithu		0	0	cn8nguyenthithu	192.168.1.235	5	504
2564	dvtranthidong		0	0	dvtranthidong	192.168.1.235	6	505
2565	cn8nguyenthihien-teamLAN		0	0	cn8nguyenthihien-teamLAN	192.168.1.235	7	506
2566	cn8dothunga		0	0	cn8dothunga	192.168.1.235	8	507
2567	cn8tranthitrang		0	0	cn8tranthitrang	192.168.1.235	9	508
2568	dvnguyenthinga		0	0	dvnguyenthinga	192.168.1.235	10	509
2569	cn8buimaitrang		0	0	cn8buimaitrang	192.168.1.235	11	510
2570	cn8khuctronghieu		0	0	cn8khuctronghieu	192.168.1.235	12	511
2571	cn8nguyenthuythuan		0	0	cn8nguyenthuythuan	192.168.1.235	13	512
2572	buithiphuongthao		0	0	buithiphuongthao	192.168.1.235	14	513
2573	dvtathiphuong		0	0	dvtathiphuong	192.168.1.235	15	514
2574	dvnguyenhongquan		0	0	dvnguyenhongquan	192.168.1.235	16	515
2575	dvnguyenhailinh		0	0	dvnguyenhailinh	192.168.1.235	17	516
2576	cn4phamductrong		0	0	cn4phamductrong	192.168.1.235	18	517
2577	bioticngkimtinh		0	0	bioticngkimtinh	192.168.1.235	19	519
2578	cn8nguyenngoccuong		0	0	cn8nguyenngoccuong	192.168.1.235	20	518
2579	cn8nguyenvancuong		0	0	cn8nguyenvancuong	192.168.1.235	21	520
2580	biotictrunghieu		0	0	biotictrunghieu	192.168.1.235	22	521
2581	biotichoangtung		0	0	biotichoangtung	192.168.1.235	23	522
2582	dvvuquangminh		0	0	dvvuquangminh	192.168.1.235	24	523
2583	cn8lothilinh		0	0	cn8lothilinh	192.168.1.235	25	524
2584	dvvumanhhao		0	0	dvvumanhhao	192.168.1.235	26	525
2585	bioticlethinhung		0	0	bioticlethinhung	192.168.1.235	27	526
2586	biotictrinhxuant		0	0	biotictrinhxuant	192.168.1.235	28	527
2587	dvhoangkimlien		0	0	dvhoangkimlien	192.168.1.235	29	528
2588	cn8hoangthuytrag		0	0	cn8hoangthuytrag	192.168.1.235	30	529
2589	cn8lethihau		0	0	cn8lethihau	192.168.1.235	31	530
2590	cn8lethihuyen		0	0	cn8lethihuyen	192.168.1.235	32	531
2591	cn8lythivui		0	0	cn8lythivui	192.168.1.235	33	532
2592	cn8phanthivan		0	0	cn8phanthivan	192.168.1.235	34	533
2593	dvnguyenthuylinh		0	0	dvnguyenthuylinh	192.168.1.235	35	534
2594	dvphamhangnga		0	0	dvphamhangnga	192.168.1.235	36	535
2595	cn8tranthithao		0	0	cn8tranthithao	192.168.1.235	37	536
2596	cn8nguyendinhkhanh		0	0	cn8nguyendinhkhanh	192.168.1.235	38	537
2597	dvtranthitrinh		0	0	dvtranthitrinh	192.168.1.235	39	538
2598	cn8trantrunghieu		0	0	cn8trantrunghieu	192.168.1.235	40	539
2599	cn8dongochuy		0	0	cn8dongochuy	192.168.1.235	41	540
2600	cn8nguyentragiang		0	0	cn8nguyentragiang	192.168.1.235	42	541
2601	cn8nguyenthian		0	0	cn8nguyenthian	192.168.1.235	43	542
2602	cn8truongthithuan		0	0	cn8truongthithuan	192.168.1.235	44	543
2603	dvcaobaodung		0	0	dvcaobaodung	192.168.1.235	45	544
2604	cn8phamkimthoa		0	0	cn8phamkimthoa	192.168.1.235	46	545
2605	cn8ngotuandung		0	0	cn8ngotuandung	192.168.1.235	47	546
2606	cn8leminhphuong		0	0	cn8leminhphuong	192.168.1.235	48	547
2607	cn8phamthuytrang		0	0	cn8phamthuytrang	192.168.1.235	49	548
2608	cn8nguyenthanhhau		0	0	cn8nguyenthanhhau	192.168.1.235	50	549
2609	cn8nguyenmaiphuong		0	0	cn8nguyenmaiphuong	192.168.1.235	51	550
2610	cn8luonghuyentrang		0	0	cn8luonghuyentrang	192.168.1.235	52	551
2611	cn8doanthihuong		0	0	cn8doanthihuong	192.168.1.235	53	552
2612	cn8nguyenthitu		0	0	cn8nguyenthitu	192.168.1.235	54	553
2613	cn8hoangthidieuhue		0	0	cn8hoangthidieuhue	192.168.1.235	55	554
2614	cn2hophuonganh		0	0	cn2hophuonganh	192.168.1.235	56	555
2615	cn2phamtienanh		0	0	cn2phamtienanh	192.168.1.235	57	556
2616	cn2nguyenthuyhang		0	0	cn2nguyenthuyhang	192.168.1.235	58	557
2617	cn2hoangvantho		0	0	cn2hoangvantho	192.168.1.235	59	558
2618	cn4dovantuan		0	0	cn4dovantuan	192.168.1.235	60	559
2619	cn2maithuylinh		0	0	cn2maithuylinh	192.168.1.235	61	560
2620	cn2nguyenthaoly		0	0	cn2nguyenthaoly	192.168.1.235	62	561
2621	cn2phamthiye		0	0	cn2phamthiye	192.168.1.235	63	562
2622	cn2hoangkhanhvi		0	0	cn2hoangkhanhvi	192.168.1.235	64	563
2623	btoanh sale		0	0	btoanh sale	192.168.1.235	65	564
2624	cn2buiminhphuong		0	0	cn2buiminhphuong	192.168.1.235	66	565
2625	cn8nguyenthihanh		0	0	cn8nguyenthihanh	192.168.1.235	67	566
2626	cn8nguyenthihang		0	0	cn8nguyenthihang	192.168.1.235	68	567
2627	cn8vuongthitam		0	0	cn8vuongthitam	192.168.1.235	69	568
2628	cn8nguyentrang-nga		0	0	cn8nguyentrang-nga	192.168.1.235	70	569
2629	cn8nguyenminhchien		0	0	cn8nguyenminhchien	192.168.1.235	71	570
2630	cn4daohaininh		0	0	cn4daohaininh	192.168.1.235	72	571
2631	lephuongthaohr		0	0	lephuongthaohr	192.168.1.235	73	572
2632	cn4dangminhtu		0	0	cn4dangminhtu	192.168.1.235	74	573
2633	cn8nguyenthituyet		0	0	cn8nguyenthituyet	192.168.1.235	75	574
2634	cn8hoangdieuthu		0	0	cn8hoangdieuthu	192.168.1.235	76	575
2635	cn8phamkimoanh		0	0	cn8phamkimoanh	192.168.1.235	77	576
2636	cn2vithuhuong		0	0	cn2vithuhuong	192.168.1.235	78	577
2637	cn2nguyenthihue		0	0	cn2nguyenthihue	192.168.1.235	79	578
2638	cn8vuthidieulinh		0	0	cn8vuthidieulinh	192.168.1.235	80	579
2639	cn8lethianh		0	0	cn8lethianh	192.168.1.235	81	580
2640	cn8nguyenthietquan		0	0	cn8nguyenthietquan	192.168.1.235	82	581
2641	cn8buiminhanh		0	0	cn8buiminhanh	192.168.1.235	83	582
2642	cn8nguyenthitrang		0	0	cn8nguyenthitrang	192.168.1.235	84	583
2643	cn8lephuonghoa		0	0	cn8lephuonghoa	192.168.1.235	85	584
2644	cn8phungthithuy		0	0	cn8phungthithuy	192.168.1.235	86	586
2645	cn8hoangthihang		0	0	cn8hoangthihang	192.168.1.235	87	587
2646	cn8nguyenmanhdung		0	0	cn8nguyenmanhdung	192.168.1.235	88	588
2647	cn8hoangvanvu		0	0	cn8hoangvanvu	192.168.1.235	89	589
2648	cn8dongoctrong		0	0	cn8dongoctrong	192.168.1.235	90	590
2649	cn8dinhvanphong		0	0	cn8dinhvanphong	192.168.1.235	91	591
2650	cn8vucongson		0	0	cn8vucongson	192.168.1.235	92	592
2651	cn8phanmaihien		0	0	cn8phanmaihien	192.168.1.235	93	593
2652	cn8hanhuhien		0	0	cn8hanhuhien	192.168.1.235	94	594
2653	cn2luongxuandien		0	0	cn2luongxuandien	192.168.1.235	95	595
2654	cn8dinhthikhanhhuyen		0	0	cn8dinhthikhanhhuyen	192.168.1.235	96	596
2655	cn8nguyenthimo		0	0	cn8nguyenthimo	192.168.1.235	97	597
2656	cn8nguyenanhtuan		0	0	cn8nguyenanhtuan	192.168.1.235	98	598
2657	cn8tothinhung		0	0	cn8tothinhung	192.168.1.235	99	599
2658	cn8buithilan		0	0	cn8buithilan	192.168.1.235	100	600
2659	ntnga cp		0	0	ntnga cp	192.168.1.235	101	601
2660	cn8phamthithom		0	0	cn8phamthithom	192.168.1.235	102	602
2661	cn8tranthichinh		0	0	cn8tranthichinh	192.168.1.235	103	603
2662	cn8tongkhanhlinh		0	0	cn8tongkhanhlinh	192.168.1.235	104	604
2663	cn8nguyenthilien		0	0	cn8nguyenthilien	192.168.1.235	105	605
2664	Lethuthao		0	0	Lethuthao	192.168.1.235	106	610
2665	pkngan cp		0	0	pkngan cp	192.168.1.235	107	611
2666	dtmchi mkt		0	0	dtmchi mkt	192.168.1.235	108	612
2667	dangquangchuong mkt		0	0	dangquangchuong mkt	192.168.1.235	109	614
2668	maithanhlong mkt		0	0	maithanhlong mkt	192.168.1.235	110	615
2669	pxmai cp		0	0	pxmai cp	192.168.1.235	111	616
2670	cn5 hangkt		0	0	cn5 hangkt	192.168.1.235	112	617
2671	cn4 dieukt		0	0	cn4 dieukt	192.168.1.235	113	618
2672	cn6 ngockt		0	0	cn6 ngockt	192.168.1.235	114	619
2673	CN3 Dungkt		0	0	CN3 Dungkt	192.168.1.235	115	620
2674	nguyennhatlehr		0	0	nguyennhatlehr	192.168.1.235	116	621
2675	vuthilamkt		0	0	vuthilamkt	192.168.1.235	117	623
2676	nhnhi mkt		0	0	nhnhi mkt	192.168.1.235	118	624
2677	vvtrung cp		0	0	vvtrung cp	192.168.1.235	119	625
2678	ntlan mkt		0	0	ntlan mkt	192.168.1.235	120	626
2679	tthanh mkt		0	0	tthanh mkt	192.168.1.235	121	627
2680	tttlinh mkt		0	0	tttlinh mkt	192.168.1.235	122	628
2681	ltthao mkt		0	0	ltthao mkt	192.168.1.235	123	629
2682	nvquyet mkt		0	0	nvquyet mkt	192.168.1.235	124	630
2683	dtathu cp		0	0	dtathu cp	192.168.1.235	125	631
2684	tvhoang mkt		0	0	tvhoang mkt	192.168.1.235	126	632
2685	vttien cp		0	0	vttien cp	192.168.1.235	127	633
2686	nkmai cp		0	0	nkmai cp	192.168.1.235	128	634
2687	ttuyen cp		0	0	ttuyen cp	192.168.1.235	129	635
2688	lkhai mkt		0	0	lkhai mkt	192.168.1.235	130	636
2689	dndiep mkt		0	0	dndiep mkt	192.168.1.235	131	637
2690	ntanh mkt		0	0	ntanh mkt	192.168.1.235	132	638
2691	ntcong mkt		0	0	ntcong mkt	192.168.1.235	133	639
2692	dvhieu mkt		0	0	dvhieu mkt	192.168.1.235	134	640
2693	ntaduong mkt		0	0	ntaduong mkt	192.168.1.235	135	641
2694	ntthuy cp		0	0	ntthuy cp	192.168.1.235	136	642
2695	ntvmai cp		0	0	ntvmai cp	192.168.1.235	137	643
2696	nthung cp		0	0	nthung cp	192.168.1.235	138	644
2697	nvhieu mkt		0	0	nvhieu mkt	192.168.1.235	139	645
2698	kthuyen cp		0	0	kthuyen cp	192.168.1.235	140	646
2699	btthanh cp		0	0	btthanh cp	192.168.1.235	141	647
2700	ntmnguyet cp		0	0	ntmnguyet cp	192.168.1.235	142	648
2701	vtbngoc cp		0	0	vtbngoc cp	192.168.1.235	143	649
2702	tkchi cp		0	0	tkchi cp	192.168.1.235	144	650
2703	pthuyen cp		0	0	pthuyen cp	192.168.1.235	145	651
2704	tmduc mkt		0	0	tmduc mkt	192.168.1.235	146	652
2705	ntquan mkt		0	0	ntquan mkt	192.168.1.235	147	653
2706	duthihang cp		0	0	duthihang cp	192.168.1.235	148	654
2707	npuyen cp		0	0	npuyen cp	192.168.1.235	149	655
2708	lhyen cp		0	0	lhyen cp	192.168.1.235	150	656
2709	dothihang cp		0	0	dothihang cp	192.168.1.235	151	657
2710	ndtanh mkt		0	0	ndtanh mkt	192.168.1.235	152	658
2711	ntvu mkt		0	0	ntvu mkt	192.168.1.235	153	659
2712	ltanh cp		0	0	ltanh cp	192.168.1.235	154	660
2713	dddat gdcn		0	0	dddat gdcn	192.168.1.235	155	661
2714	pqanh mkt		0	0	pqanh mkt	192.168.1.235	156	662
2715	ltynhi cp		0	0	ltynhi cp	192.168.1.235	157	663
2716	vtyen sale		0	0	vtyen sale	192.168.1.235	158	664
2717	bttphuong sale		0	0	bttphuong sale	192.168.1.235	159	665
2718	ttsang sale		0	0	ttsang sale	192.168.1.235	160	666
2719	nguyenthiphuong cp		0	0	nguyenthiphuong cp	192.168.1.235	161	667
2720	phamdieuhien gdcn		0	0	phamdieuhien gdcn	192.168.1.235	162	668
2721	duongthihue cp		0	0	duongthihue cp	192.168.1.235	163	669
2722	nguyenthihuonglan cp		0	0	nguyenthihuonglan cp	192.168.1.235	164	670
2723	phammanhquan mkt		0	0	phammanhquan mkt	192.168.1.235	165	671
2724	nguyenduyhai cp		0	0	nguyenduyhai cp	192.168.1.235	166	672
2725	nguyentrunghieu gdcn		0	0	nguyentrunghieu gdcn	192.168.1.235	167	673
2726	hoangthithuha cp		0	0	hoangthithuha cp	192.168.1.235	168	674
2727	ncnlinh cp		0	0	ncnlinh cp	192.168.1.235	169	675
2728	trananhtuan mkt		0	0	trananhtuan mkt	192.168.1.235	170	676
2729	trantrungkien mkt		0	0	trantrungkien mkt	192.168.1.235	171	677
2730	daohongngoc cp		0	0	daohongngoc cp	192.168.1.235	172	678
2731	phamminhduc mkt		0	0	phamminhduc mkt	192.168.1.235	173	679
2732	nguyenthuhoai cp		0	0	nguyenthuhoai cp	192.168.1.235	174	680
2741	Nguyen Van Tien	123456	3	0	Nguyễn Văn Tiến	192.168.1.235	175	12345
2744	Nguyen Van Tien	123456	3	0	Nguyễn Văn Tiến	192.168.1.235	176	12345
2754	Tien	123456	0	0	Tien	192.168.1.201	1	1000
2755	88		14	0	88	192.168.1.201	2	1
2756	Nguyen Van Tien	123456	3	0	Nguyen Van Tien	192.168.1.201	3	12345
\.


--
-- TOC entry 3395 (class 0 OID 33293)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240919083553_initial	8.0.8
20240920044533_editnotification1	8.0.8
\.


--
-- TOC entry 3413 (class 0 OID 0)
-- Dependencies: 216
-- Name: Attendances_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Attendances_Id_seq"', 14, true);


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 226
-- Name: DeviceEmployees_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."DeviceEmployees_Id_seq"', 1, false);


--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 218
-- Name: Devices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Devices_Id_seq"', 34, true);


--
-- TOC entry 3416 (class 0 OID 0)
-- Dependencies: 220
-- Name: Employees_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Employees_Id_seq"', 2756, true);


--
-- TOC entry 3417 (class 0 OID 0)
-- Dependencies: 222
-- Name: Notifications_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Notifications_Id_seq"', 11, true);


--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 224
-- Name: Sheets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sheets_Id_seq"', 39, true);


--
-- TOC entry 3235 (class 2606 OID 33303)
-- Name: Attendances PK_Attendances; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attendances"
    ADD CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id");


--
-- TOC entry 3248 (class 2606 OID 33346)
-- Name: DeviceEmployees PK_DeviceEmployees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DeviceEmployees"
    ADD CONSTRAINT "PK_DeviceEmployees" PRIMARY KEY ("Id");


--
-- TOC entry 3237 (class 2606 OID 33311)
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY ("Id");


--
-- TOC entry 3239 (class 2606 OID 33319)
-- Name: Users PK_Employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- TOC entry 3241 (class 2606 OID 33327)
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- TOC entry 3244 (class 2606 OID 33335)
-- Name: Sheets PK_Sheets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "PK_Sheets" PRIMARY KEY ("Id");


--
-- TOC entry 3233 (class 2606 OID 33297)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3245 (class 1259 OID 33357)
-- Name: IX_DeviceEmployees_DeviceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DeviceEmployees_DeviceId" ON public."DeviceEmployees" USING btree ("DeviceId");


--
-- TOC entry 3246 (class 1259 OID 33358)
-- Name: IX_DeviceEmployees_EmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DeviceEmployees_EmployeeId" ON public."DeviceEmployees" USING btree ("EmployeeId");


--
-- TOC entry 3242 (class 1259 OID 33359)
-- Name: IX_Sheets_DeviceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sheets_DeviceId" ON public."Sheets" USING btree ("DeviceId");


--
-- TOC entry 3250 (class 2606 OID 33347)
-- Name: DeviceEmployees FK_DeviceEmployees_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DeviceEmployees"
    ADD CONSTRAINT "FK_DeviceEmployees_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- TOC entry 3251 (class 2606 OID 33352)
-- Name: DeviceEmployees FK_DeviceEmployees_Employees_EmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DeviceEmployees"
    ADD CONSTRAINT "FK_DeviceEmployees_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3249 (class 2606 OID 33336)
-- Name: Sheets FK_Sheets_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sheets"
    ADD CONSTRAINT "FK_Sheets_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


-- Completed on 2024-10-13 10:50:19 UTC

--
-- PostgreSQL database dump complete
--

