export const RequestTypes = {
    AddDevice: "AddDevice",
    RemoveDevice: "RemoveDevice",
    UpdateDevice: "UpdateDevice",
    ConnectDevice: "ConnectDevice",
    GetDevices: "GetAllDevice",
    GetUsers: "GetUsers",
    DisconnectDevice: "DisconnectDevice",
    AddUser: "AddUser",
    GetAttendances: "GetAttendances",
    DeleteUser: "DeleteUser",
    GetAllUsers: "GetAllUsers",
    SyncData: "SyncData",
    GetSheets: "GetSheets",
    SyncUserData: "SyncUserData",
    SyncLogData: "SyncLogData",
    UpdateEmail: "UpdateEmail",
    GetSettings: "GetSettings",
    GetUsersByDeviceId: "GetUsersByDeviceId",
    UpdateLog: "UpdateLog",
    DeleteLog: "DeleteLog",
    AddLog: "AddLog",
    SyncDataFromSheet: "SyncDataFromSheet",
    EditUser: "EditUser",
    SyncTime: "SyncTime"
}
